config/routes.rb
Waxtracker::Application.routes.draw do
  get "dashboard" => "dashboard#index"
  get "static_pages/index"
  devise_for :users
  resources :records

  root "static_pages#index"

  

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :users, :foreign_key => "user_id"
  # attr_accessible :album_title
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :records
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def stored_location_for!(resource)
    nil
  end

  def after_sign_in_path_for(resource)
    '/dashboard/'    
  end 
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /records
  # GET /records.json
  def index
      @records = current_user.records
  end

  # GET /records/1
  # GET /records/1.json
  def show
    unless current_user.id == @record.user_id
      flash[:notice] = "You may only view your own products."
      redirect_to root_path
    end
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
      
      rescue ActiveRecord::RecordNotFound
        redirect_to root_url, :flash => { :notice => "Record not found." }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:album_title)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
    puts '&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    puts 'made it'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dashboard/index.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="active"><a href="#">Home</a></li>
   <li><a href="#">Records</a></li>
   <li><a href="#">Artists</a></li>
   <li><a href="#">Playlists</a></li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span><span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button> 

    <% if user_signed_in? %>
      <li>
        <a class="navbar-brand" href="/dashboard">
          <%= image_tag('logo.png', id: 'logo') %>
        </a>        
      </li>
    <% else %>
      <li>
        <a class="navbar-brand" href="/">
          <%= image_tag('logo.png', id: 'logo') %>
        </a>
      </li>
    <% end %>
  </div>
        
  <div class="collapse navbar-collapse">

    <!-- <ul class="nav navbar-nav">

      <li class="active">
        <a href="#">Link</a>
      </li>
      <li>
        <a href="#">Link</a>
      </li>
      <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
        <ul class="dropdown-menu">
          <li>
            <a href="#">Action</a>
          </li>
          <li>
            <a href="#">Another action</a>
          </li>
          <li>
            <a href="#">Something else here</a>
          </li>
          <li class="divider">
          </li>
          <li>
            <a href="#">Separated link</a>
          </li>
          <li class="divider">
          </li>
          <li>
            <a href="#">One more separated link</a>
          </li>
        </ul>
      </li>
    </ul> -->

    <!-- <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" />
      </div> <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="#" class='btn btn-default'>About</a>
      </li>

      <li>
        <a href="#" class='btn btn-default'>Features</a>
      </li>

      <li>
        <a href="#" class='btn btn-default'>FAQ</a>
      </li>

      <li>
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'btn btn-default') %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path, :class => 'btn btn-default')  %>  
          </li>
        <% end %>
      </li>
      
    </ul>
  </div>
  
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waxtracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body style='background:#494949;'>
  
  <%= render 'layouts/navbar' %>

<div style='margin-top:70px;'class="container" style='text-align:center;'>

  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>
  
  <div class="row">
    <%= yield %>
  </div>







</div>
</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Brand</a>
        </div>
        
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active">
              <a href="#">Link</a>
            </li>
            <li>
              <a href="#">Link</a>
            </li>
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="#">Action</a>
                </li>
                <li>
                  <a href="#">Another action</a>
                </li>
                <li>
                  <a href="#">Something else here</a>
                </li>
                <li class="divider">
                </li>
                <li>
                  <a href="#">Separated link</a>
                </li>
                <li class="divider">
                </li>
                <li>
                  <a href="#">One more separated link</a>
                </li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" />
            </div> <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="#">Link</a>
            </li>
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="#">Action</a>
                </li>
                <li>
                  <a href="#">Another action</a>
                </li>
                <li>
                  <a href="#">Something else here</a>
                </li>
                <li class="divider">
                </li>
                <li>
                  <a href="#">Separated link</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        
      </nav>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_title %><br>
    <%= f.text_field :album_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <thead>
    <tr>
      <th>Album title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.album_title %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album title:</strong>
  <%= @record.album_title %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>